<link rel="stylesheet" href="<c:url value='/templates/user/assets/css/bootstrap.min.css' />">
<link rel="stylesheet" href="<c:url value='/templates/user/assets/css/owl.carousel.min.css' />">
<link rel="stylesheet" href="<c:url value='/templates/user/assets/css/flaticon.css' />">
<link rel="stylesheet" href="<c:url value='/templates/user/assets/css/slicknav.css' />">
<link rel="stylesheet" href="<c:url value='/templates/user/assets/css/animate.min.css' />">
<link rel="stylesheet" href="<c:url value='/templates/user/assets/css/magnific-popup.css' />">
<link rel="stylesheet" href="<c:url value='/templates/user/assets/css/fontawesome-all.min.css' />">
<link rel="stylesheet" href="<c:url value='/templates/user/assets/css/themify-icons.css' />">
<link rel="stylesheet" href="<c:url value='/templates/user/assets/css/slick.css' />">
<link rel="stylesheet" href="<c:url value='/templates/user/assets/css/nice-select.css' />">
<link rel="stylesheet" href="<c:url value='/templates/user/assets/css/style.css' />">